Bugfix: Default value of headers should be empty dict
We return informative JSON errors to users, and in cases where
the headers attribute was initialized to None, when we try to set
`Content-Type` later on in the proxy logic, we will get an error:

TypeError: 'NoneType' object does not support item assignment

We can resolve this by setting the default value of headers to
an empty dict.